### ISSUE TITLE
unnecessary symbol

### ISSUE THREAD

**Issue by loveunicom** [MicrosoftDocs/azure-docs-powershell.zh-CN#11]
unnecessary symbols appear in following sentence：
为方便起见，以下脚本将会卸载__除__ AzureRM 最新版本之外的所有 AzureRM 版本。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fd192f26-d3eb-6413-2d1b-7b5d8b7c37f7
* Version Independent ID: 9a312576-d1c8-6a00-c1ff-b52677b16e17
* Content: [卸载 Azure PowerShell](https://docs.microsoft.com/zh-cn/powershell/azure/uninstall-azurerm-ps?view=azurermps-6.13.0)
* Content Source: [docs-conceptual/azurermps-6.13.0/uninstall-azurerm-ps.md](https://github.com/azure/azure-docs-powershell.zh-CN/blob/live/docs-conceptual/azurermps-6.13.0/uninstall-azurerm-ps.md)
* Service: **azure-powershell**
* GitHub Login: @sptramer
* Microsoft Alias: **sttramer**

**Comment by CeciAc** [comment]
Closing this issue since it was on a previous version of the page
